// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
   return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBJP1iZSR3FURtE4YL5zC_N82yYi5jO7eg",
    authDomain: "aluga-instrumental.firebaseapp.com",
    projectId: "aluga-instrumental",
    storageBucket: "aluga-instrumental.firebasestorage.app",
    messagingSenderId: "584837803238",
    appId: "1:584837803238:web:4bfad16c4cb0c68b6b9f27",
    measurementId: "G-EZXT69H3G4"
  );

}
